# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
      ports: 5432